[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ChatKokkos"
dynamic = ["version"]
description = "ChatHPC project for Kokkos."
readme = "README.md"
requires-python = ">=3.8"
keywords = []
authors = [
  { name = "Aaron Young", email = "youngar@ornl.gov" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "codellama @ git+ssh://git@github.com/meta-llama/codellama.git@main",
  "peft==0.14.0",
  "transformers==4.48.0",
  "accelerate==1.2.1",
  "datasets",
  "bitsandbytes",
  "protobuf",
  "ipykernel",
  "ipython",
  "ipywidgets",
  "jupyter",
  "nbdime",
  "wandb",
]

[tool.hatch.metadata]
allow-direct-references = true

[project.urls]
Documentation = "https://code.ornl.gov/ChatHPC/ChatKokkos#readme"
Homepage = "https://code.ornl.gov/ChatHPC/ChatKokkos"
Issues = "https://code.ornl.gov/ChatHPC/ChatKokkos/-/issues"
Source = "https://code.ornl.gov/ChatHPC/ChatKokkos"

[project.scripts]
ChatKokkos-add1 = "chatkokkos.add:main"

[tool.hatch.version]
path = "src/chatkokkos/__about__.py"

[tool.hatch.env]
requires = [
  "hatch-mkdocs",
]

[tool.hatch.env.collectors.mkdocs.docs]
path = "mkdocs.yml"

[tool.hatch.envs.docs]

[tool.hatch.envs.default]
dependencies = [
  "coverage[toml]>=6.5",
  "pytest",
  "pre-commit",
]
[tool.hatch.envs.default.scripts]
test = "pytest {args:tests}"
test-cov = "coverage run -m pytest {args:tests}"
cov-report = [
  "- coverage combine",
  "coverage report",
  "coverage xml -o coverage.xml",
]
cov-html = [
  "test-cov",
  "cov-report",
  "coverage html",
]
cov = [
  "test-cov",
  "cov-report",
]

[[tool.hatch.envs.all.matrix]]
python = ["3.8", "3.9", "3.10", "3.11", "3.12"]

[tool.hatch.envs.types]
dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/chatkokkos tests}"

[tool.coverage.run]
source_pkgs = ["chatkokkos", "tests"]
branch = true
parallel = true
omit = [
  "src/chatkokkos/__about__.py",
]

[tool.coverage.paths]
chatkokkos = ["src/chatkokkos", "*/ChatKokkos/src/chatkokkos"]
tests = ["tests", "*/ChatKokkos/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
  "raise AssertionError",
  "raise RuntimeError",
  "raise NotImplementedError",
  "pass",
  "raise ValueError",
]

[tool.coverage.html]
directory = "coverage_html_report"

[tool.hatch.envs.hatch-static-analysis]
dependencies = ["ruff==0.6.4"]
config-path = "ruff_defaults.toml"

[tool.ruff]
extend = "ruff_defaults.toml"

[tool.ruff.lint]
extend-ignore = [
  "T201",   # `print` found
  "FBT001", # Boolean-typed positional argument in function definition
  "FBT002", # Boolean default positional argument in function definition
  "EM101",  # Raw string in Exception
  "TRY003", # Avoid long strings in Exception Class.
]
